### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by stefs22** [vladmandic/stream-rtsp#15]
I want to install this on pi, but i dont know where to start, advice?

**Comment by vladmandic** [comment]
did you follow the readme? not sure what i can do based on your single line.

**Comment by stefs22** [comment]
Ur name is Vladimir, do u speak serbian?

**Comment by vladmandic** [comment]
croatian. similar.

**Comment by stefs22** [comment]
Tako reci brate.
Ajde objasnicu ovako malo duze pa mozda dodjemo do resenja.
Naime, imam 3 reolink kamere preko rtsp linka, kada ih pustim preko vlc-a rade top.
Kada ih pustim na raspberry pi-u (zelim da napravim od njega cctv viewer), one seckaju i to bas.
Bilo koji program da probam jednostavno seckaju, sem na VLC, ali zelim da napravim da se autimatski pale kad se pali pi.
E sad, zelio bih da vidim da ih prebacim u neke od formata i tako probam, mozda bude stabilnije.
Ako nista ne uspe skinucu neki program za kablovsku i gledacu ih kao kanale na split screen.

**Comment by vladmandic** [comment]
> ali zelim da napravim da se autimatski pale kad se pali pi, sve 3, a vlc to nemoze

zasto ne? mozes napraviti skriptu koja starta vlc sa potrebnim parametrima i da se skripta starta xx sekundi nakon logina.

> E sad, zelio bih da vidim da ih prebacim u neke od formata i tako probam, mozda bude stabilnije.

ovaj projekt bi mogao raditi, ali iskreno rpi nema bas puno cpu snage cak i za jednostavni task ala ovo.
ako i radi, cpu ce stalno biti na 100%. ali mozes probati - nisi rekao u cemu je problem?

**Comment by stefs22** [comment]
Mogu staviti task da pali vlc po pokretanju, ali nisam siguran mogu li staviti da pali 3 kamere na split screen.

Problem je u tome sto neznam sta da uradim jer sam pocetnik, citam i ne razumem. 
Znaci, upalim pi, sta dalje?
Moze li se jednom upaliti, convertovati i to je to, predpostavljam da stalno mora biti upaljen kako bi radio konvertovani strim?

**Comment by vladmandic** [comment]
> Mogu staviti task da pali vlc po pokretanju, ali nisam siguran mogu li staviti da pali 3 kamere na split screen.

ako mozes napraviti rucno kada sam startas vlc, sigurno postoje parametri da naprave to isto iz taska. ali nije da znam vlc parametre napament.

> Moze li se jednom upaliti, convertovati i to je to, predpostavljam da stalno mora biti upaljen kako bi radio konvertovani strim?

kamera salje stream - i taj stream browser ne razumije, zato ovaj projekt - da konvertira stream u format koji browser razumije.
ako koristis vlc, onda ovaj projekt nije potreban jer vlc vec zna raditi sa originalnim stream-om.

zbilja ne mogu ovdje napraviti nikakav detaljniji "install guide" od ovoga sta vec postoji jer je previse varijabli. razlicite verzije linuxa, paths, etc.

**Comment by stefs22** [comment]
Hvala, problem je sto nema informacija o tome da se otvore 3 vlc prozora koja ce biti podeljena po ekranu, zato bih probao ovo da vidim kakav ce biti strim.
Ono sto me zanima, znaci upalim u pi, u terminal ukucam
**npm run build**
pa onda 
**config.json** i podesim?

**Comment by vladmandic** [comment]
da, ako imas nodejs vec instaliran i npm module instaliran. onda dolazi `npm run build`
