### ISSUE TITLE
docker problem

### ISSUE THREAD

**Issue by JasonKe1031** [vladmandic/stream-rtsp#17]
hey guys,I tried to deploy this service to docker, but I encountered this problem. Can anyone with similar experience give some hints to solve this problem?
![image](https://user-images.githubusercontent.com/68834574/231666147-90306092-ae5e-4883-bcf3-0327dcbc0f83.png)

**Comment by JasonKe1031** [comment]
and this is my cmd:
![image](https://user-images.githubusercontent.com/68834574/231667725-69c73879-5024-4027-b25f-bc8e75034a00.png)

**Comment by vladmandic** [comment]
you've posted screenshot, but what is the actual problem?

**Comment by vladmandic** [comment]
closing as no info provided.
