### ISSUE TITLE
Error on Build

### ISSUE THREAD

**Issue by fraeggle** [vladmandic/stream-rtsp#21]
Hi
i am using a Pi with bullseye. I always get a Build error.
What am i doing wrong? 

pi@AgentDVR:~/stream-rtsp $ nodejs -v
v12.22.12

pi@AgentDVR:~/stream-rtsp $ sudo npm run build

> stream-rtsp@0.1.1 build
> cd stream; go clean; go get ./...; go build -ldflags='-s -w' .; cd ..

sh: 1: go: not found
sh: 1: go: not found
sh: 1: go: not found

pi@AgentDVR:~/stream-rtsp $ ls
client       favicon.ico  package.json  server
config.json  LICENSE      README.md     stream

pi@AgentDVR:~/stream-rtsp $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
pi@AgentDVR:~/stream-rtsp $

Regards Peter

**Comment by fraeggle** [comment]
ok think i found the issue. 
"..
    npm run build
Which installs all required GoLang dependencies...."  Only if golang is installed on the system......
One step further.

now i get:

pi@AgentDVR:~/stream-rtsp $ npm run build

> stream-rtsp@0.1.1 build
> cd stream; go clean; go get ./...; go build -ldflags='-s -w' .; cd ..

go: updates to go.sum needed, disabled by -mod=readonly
go: updating go.sum: open /home/pi/stream-rtsp/stream/go.sum: permission denied
go: updates to go.sum needed, disabled by -mod=readonly

pi@AgentDVR:~/stream-rtsp $ npm start

> stream-rtsp@0.1.1 start
> node server/serve

/home/pi/stream-rtsp/server/serve.js:92
      if (result?.stat?.isFile()) {
                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/pi/stream-rtsp
npm ERR! command failed
npm ERR! command sh -c node server/serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-09-07T18_14_49_434Z-debug.log
LOGFile:
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 13ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 23ms
5 timing config:load:builtin Completed in 24ms
6 timing config:load:cli Completed in 20ms
7 timing config:load:env Completed in 3ms
8 timing config:load:file:/home/pi/stream-rtsp/.npmrc Completed in 2ms
9 timing config:load:project Completed in 15ms
10 timing config:load:file:/home/pi/.npmrc Completed in 1ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 2ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 12ms
17 timing config:load:setEnvs Completed in 7ms
18 timing config:load Completed in 103ms
19 verbose npm-session db2fc098b42960e1
20 timing npm:load Completed in 171ms
21 timing command:run-script Completed in 682ms
22 timing command:start Completed in 697ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (events.js:314:20)
23 verbose stack     at maybeClose (internal/child_process.js:1022:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
24 verbose pkgid stream-rtsp@0.1.1
25 verbose cwd /home/pi/stream-rtsp
26 verbose Linux 6.1.21-v8+
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v12.22.12
29 verbose npm  v7.5.2
30 error code 1
31 error path /home/pi/stream-rtsp
32 error command failed
33 error command sh -c node server/serve
34 verbose exit 1

**Comment by vladmandic** [comment]
a lot of stuff in related packages have changed since i've published this package and i don't actively maintain it.
if someone wants to contribute a pr, i'd be happy to look at it, otherwise, i'm closing.
