### ISSUE TITLE
Can run this on Windows?

### ISSUE THREAD

**Issue by Barabba11** [vladmandic/stream-rtsp#22]
Hi mate! Sorry for opening an issue just for a question, I hope it can be useful for someone else.
I have a Windows server, I need to see (as simply as possible) a local camera on any phone connected by WiFi, using QR code (contaning URL of the local server). 
Network is not a problem for me, I would use WebRTC on Windows IIS, do you know how? Maybe I've to install nodejs on Windows? NPM too? Thank you a lot!

PS: for each new connection the script will ask camera for a new RTSP stream? Is eventaully possible the server will keep connecting to camera once and copy stream (unicast or multicast) to requiring phones?

**Comment by vladmandic** [comment]
re: windows - yes, but you'll need to recompile, not just use as-is
re: unicast/multicast - in theory, but i have not explored those options.
