### ISSUE TITLE
Connect from local machine to Cloud Virtual Machine 

### ISSUE THREAD

**Issue by gigwegbe** [vladmandic/stream-rtsp#5]
Hello @vladmandic,
I recently can across your stream-rtsp project, so far I have successfully run it on my local machine. However, I want to be able to view my local rtsp stream on a  cloud virtual machine. What approach will you recommend? also, do I need to set up a turn/stun server for this project? Thanks

**Comment by vladmandic** [comment]
@gigwegbe this package is intended to work in peer-to-peer mode and as long as server and client ips are directly reachable, it should be ok regardless of location. it's not intended to work with stun server as-is (although it could be made to work, but it would require implementing an additional handshake).
