### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by tux-** [vladmandic/stream-rtsp#6]
Tested out the WebRTC, which works great with low latency on Desktop. How ever, on an Android device on the same local network the video will not load. Not sure if this is a valid ticket here or not, this was the only place I could think of to post a question. Is it possible, and if so, how to enable Android support?

**Comment by vladmandic** [comment]
I've never tested it on android, but I don't see why it wouldn't work as long as client app supports webrtc streams  
i know chrome for android supports webrtc, but no idea about the rest, so check whats the client app capability

**Comment by tux-** [comment]
Yeah, I agree! I tried my best to search for this to figure out what this could be, not successful so far. Tested on multiple devices, none work, default Android chrome browser. Might just have to make two different versions of my stream, one for Android, and one for Desktop ;) Thanks for the reply!

**Comment by vladmandic** [comment]
If you attach dev tools to chrome on android, what does console log show?

**Comment by tux-** [comment]
From what I can find: `const data = res && res.ok ? await res.text() : '';` the `res.text()` returns an empty string. The rest of the request seems fine to me. The data sent into the body of the stream/reciever might be of interest, and it reads as follows:

```
v=0
o=- 7263735025820665317 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 124 101 102
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:FFxD
a=ice-pwd:OeeklTfLR2Xlimd32aW5bmr3
a=ice-options:trickle
a=fingerprint:sha-256 B7:BF:7B:B0:00:F2:46:83:30:F6:21:34:F5:86:7E:60:5C:CE:32:08:89:1C:EC:6E:E4:AF:7D:3B:B2:B8:CF:F5
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- 60f9d419-9ded-4e82-884e-5a47c908b766
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:124 red/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=124
a=rtpmap:102 ulpfec/90000
a=ssrc-group:FID 2962500185 3763020948
a=ssrc:2962500185 cname:EdhGA6DMzdZtENE2
a=ssrc:2962500185 msid:- 60f9d419-9ded-4e82-884e-5a47c908b766
a=ssrc:2962500185 mslabel:-
a=ssrc:2962500185 label:60f9d419-9ded-4e82-884e-5a47c908b766
a=ssrc:3763020948 cname:EdhGA6DMzdZtENE2
a=ssrc:3763020948 msid:- 60f9d419-9ded-4e82-884e-5a47c908b766
a=ssrc:3763020948 mslabel:-
a=ssrc:3763020948 label:60f9d419-9ded-4e82-884e-5a47c908b766
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:FFxD
a=ice-pwd:OeeklTfLR2Xlimd32aW5bmr3
a=ice-options:trickle
a=fingerprint:sha-256 B7:BF:7B:B0:00:F2:46:83:30:F6:21:34:F5:86:7E:60:5C:CE:32:08:89:1C:EC:6E:E4:AF:7D:3B:B2:B8:CF:F5
a=setup:actpass
a=mid:1
a=sctp-port:5000
a=max-message-size:262144
```

I got hold of a more expensive (but older) Android device now, and there it works good. So, it might be a problem with cheap Android devices? The debug comes from a Moto G20

**Comment by vladmandic** [comment]
> From what I can find: const data = res && res.ok ? await res.text() : ''; the res.text() returns an empty string. 

That part has nothing to do with client capabilities, that's a simple request to WebRTC server to get stream info that will be used to create WebRTC client connection. No chance that result can be different between desktop and mobile.

> I got hold of a more expensive (but older) Android device now, and there it works good. So, it might be a problem with cheap Android devices? The debug comes from a Moto G20

No idea.  
I just tried on my old **S10+** and new **S21 Ultra** and it works fine, I don't have any other devices available.

**Comment by tux-** [comment]
Checked the log from the server, which reads:

`WriteHeader unable to start track, codec is not supported by remote`

Does that mean that WebRTC is not supported in general, or does it mean that there is another codec that could be chosen instead?

**Comment by vladmandic** [comment]
Ahh, that's starting to make sense (a little bit)...

WebRTC is a transport while the stream itself can be encoded in any number of codecs (most commonly AVC variation of H.264, but there is no rule it that it has to be). So client needs to understand a) how to negotiate WebRTC, b) how to actually decode a stream.

Now, in case of Chrome, it has a wide codec support, but it will internally disable codecs that it thinks it cannot reliably run because platform itself does not have sufficient HW acceleration so experience is smooth.

So on "better" HW, everything just works while on lower end hardware Chrome does initial WebRTC handshake, but then responds with "codec is not supported". Only solution for that would be to run re-encoding of the stream on server-side, but that is quite resource intensive and beyond the scope of what I have.

**Comment by tux-** [comment]
Ah, yes this makes sense! Thank you so much for investing time into this :) If someone else stumble on to this issue, I guess possible fixes include re-encoding as described above, or maybe check if `data` is an empty string, and then redirect to alternative stream. I will probably choose to just not support those devices as it is not important enough for current smart home project.

**Comment by vladmandic** [comment]
Glad we've figured it out, although it's not exactly a wrapped-up solution :)
