### ISSUE TITLE
Browser crash with using facetime camera feed

### ISSUE THREAD

**Issue by geohuz** [vladmandic/stream-rtsp#8]
I use ffmpeg to produce rtsp stream and publish to rtsp-simple-server on one of my macbook (https://github.com/aler9/rtsp-simple-server/releases),
```
ffmpeg \
                                  -f avfoundation \
                                  -pix_fmt yuyv422 \
                                  -video_size 640x480 \
                                  -framerate 30 \
                                  -i "0:0" -ac 2 \
                                  -vf format=yuyv422 \
                                  -vcodec libx264 -maxrate 2000k \
                                  -bufsize 2000k -acodec aac -ar 44100 -b:a 128k \
                                  -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/mystream
```

the config.json:
```
{
  "server": {
    "httpPort": 8000,
    "httpsPort": 8001,
    "encoderPort": ":8002",
    "iceServers": [],
    "webrtcMinPort": 32768,
    "webrtcMaxPort": 65535,
    "retryConnectSec": 5,
    "startStreamServer": true
  },
  "streams": {
    "main": {
      "VOD": true,
      "disableAudio": true,
      "debug": true,
      "url": "rtsp://192.168.31.223:8554/mystream"
    }
  },
  "client": {
    "debug": true,
    "defaultStream": "main"
  }
}
```

The browser simply display "oops" after showing loading circle of the video element for a while. The console message:
```
08:42:55.538 webrtc client starting
webrtc.js:8 08:42:55.538 webrtc server: http://127.0.0.1:8002 stream: main
App.js:46 start play video
webrtc.js:8 08:42:55.542 webrtc received streams: [{…}]
webrtc.js:8 08:42:55.552 webrtc negotiation start: RTCSessionDescription {type: 'offer', sdp: 'v=0\r\no=- 2810345749065350878 2 IN IP4 127.0.0.1\r\ns…:1\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n'}
webrtc.js:8 08:42:55.553 webrtc connection checking
webrtc.js:8 08:42:55.554 webrtc received track: MediaStreamTrack {kind: 'video', id: '72144351-2db0-47e1-9ed7-2de1bbe02805', label: '72144351-2db0-47e1-9ed7-2de1bbe02805', enabled: true, muted: true, …} {deviceId: '72144351-2db0-47e1-9ed7-2de1bbe02805', resizeMode: 'none'}
webrtc.js:8 08:42:55.602 webrtc connection connected
webrtc.js:8 08:42:55.605 webrtc channel open
```

**Comment by vladmandic** [comment]
it sounds like media stream decoder in browser itself is buggy and doesn't like the particular stream format you're outputing  
first things first, i'd try some other settings for the video stream, but other than that not sure how much i can help if browser crashes. in general, **any** js code runs in a sandbox and should not crash a browser, so by definition its a browser issue  
(and you didn't even say which browser)

**Comment by geohuz** [comment]
Oh, sorry, I should mention it's latest Chrome on mac, and here is the screen shot:
<img width="726" alt="Screen Shot 2022-05-11 at 18 47 50" src="https://user-images.githubusercontent.com/730770/167832404-cd703ceb-6bdd-43a0-b580-8e18abd4bc1a.png">

and I've tested with vlc and works fine.

**Comment by vladmandic** [comment]
chome on mac is problematic as apple does not allow usage of all usual libraries that chrome relies on, so its quite some patchwork by google to make it work at all.

but other than what i said (try some different codec configurations), i don't have other suggestions. whatever the root cause is, its deep inside chrome.

**Comment by geohuz** [comment]
stream server: [24 Type need add next version report https://github.com/deepch/vdk][24 Type need add next version report https://github.com/deepch/vdk]```

**Comment by vladmandic** [comment]
so staying with x264 codec, but switching format from yuv422 to yup420p works on chrome/mac - good to know  

it depends on a browser which codecs it supports for webrtc, i don't know about chrome on mac  
take a look at <https://developer.mozilla.org/en-US/docs/Web/Media/Formats/WebRTC_codecs>

**Comment by geohuz** [comment]
I solve the audio problem by specifying the codec to libopus:

```
ffmpeg -f avfoundation -framerate 30 -i "0:0" -c:a pcm_mulaw -vcodec libx264 -preset     ultrafast  -b:v 400k -pix_fmt yuv420p -c:a libopus -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/mystream
